// swift-tools-version: 5.9
// NOTE: This Package.swift is provided for reference and IDE support.
// The actual build is driven by Family4.xcodeproj (generated by the CI setup script).
// To open in Xcode: open ios/Family4.xcodeproj

import PackageDescription

let package = Package(
    name: "Family4",
    platforms: [
        .iOS(.v16)
    ],
    products: [
        .library(name: "Family4", targets: ["Family4"]),
        .library(name: "Family4Widget", targets: ["Family4Widget"]),
    ],
    dependencies: [],
    targets: [
        .target(
            name: "Family4",
            path: "Family4",
            exclude: ["Resources/Info.plist"],
            resources: [
                .process("Resources")
            ]
        ),
        .target(
            name: "Family4Widget",
            path: "Family4Widget"
        ),
        .testTarget(
            name: "Family4Tests",
            dependencies: ["Family4"],
            path: "Family4Tests"
        ),
    ]
)
